In [110]:
# Survived

In [111]:
import numpy as np
import pandas as pd

In [112]:
df = pd.read_csv('titanic.csv' , usecols=['Survived' ,'Pclass' , 'Age' , 'Sex' , 'SibSp' , 'Parch' ,'Fare' , 'Embarked'])

In [113]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [114]:
df.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  34.5      0      0   7.8292        Q
1         1       3  female  47.0      1      0   7.0000        S
2         0       2    male  62.0      0      0   9.6875        Q
3         0       3    male  27.0      0      0   8.6625        S
4         1       3  female  22.0      1      1  12.2875        S

In [115]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [116]:
from sklearn.impute import SimpleImputer

# Impute missing values in the 'Age' column with the mean
si = SimpleImputer()
df['Age'] = si.fit_transform(df[['Age']])
df['Fare'] = si.fit_transform(df[['Fare']])

In [117]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [118]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Sex'] = le.fit_transform(df['Sex'])
df['Age'] = le.fit_transform(df['Age'])
df['Embarked'] = le.fit_transform(df['Embarked'])

In [119]:
df.head()

Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked
0         0       3    1   45      0      0   7.8292         1
1         1       3    0   61      1      0   7.0000         2
2         0       2    1   75      0      0   9.6875         1
3         0       3    1   34      0      0   8.6625         2
4         1       3    0   27      1      1  12.2875         2

In [120]:
x = df.drop(columns= ['Survived'])
y = df['Survived']

In [ ]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x, y , test_size=0.2 , random_state=42)

In [122]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train_sc = sc.fit_transform(x_train)
x_test_sc = sc.transform(x_test)

In [123]:
from sklearn.naive_bayes import  BernoulliNB
classifier = BernoulliNB()
classifier.fit(x_train_sc,y_train)
BernoulliNB()

BernoulliNB()

In [124]:
y_pred = classifier.predict(x_train_sc)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,

In [125]:
from sklearn.metrics import confusion_matrix

# Generate predictions for the test set
y_pred_test = classifier.predict(x_test_sc)

# Compute the confusion matrix
cn = confusion_matrix(y_test, y_pred_test)

In [126]:
cn

array([[50,  0],
       [ 0, 34]], dtype=int64)

In [127]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_test)

1.0

In [128]:
from sklearn.metrics import precision_score
precision_score(y_test,y_pred_test)

1.0

In [129]:
from sklearn.metrics import recall_score
recall = recall_score(y_test , y_pred_test)
recall

1.0

In [130]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

# Fit the model
lr.fit(x_train, y_train)

# Make predictions
y_pred_lr = lr.predict(x_test)
y_pred_lr


array([ 1.06581410e-14,  1.00000000e+00,  1.09912079e-14,  1.04360964e-14,
        1.00000000e+00, -3.88578059e-15,  1.00000000e+00, -1.67643677e-14,
        1.00000000e+00,  1.06581410e-14,  1.02140518e-14,  1.00000000e+00,
        1.00000000e+00,  1.00000000e+00,  1.06581410e-14,  1.06581410e-14,
        1.00000000e+00, -1.68753900e-14,  8.21565038e-15, -2.88657986e-15,
       -3.55271368e-15, -1.69864123e-14,  1.00000000e+00, -2.66453526e-15,
        1.00000000e+00,  1.00000000e+00,  1.00000000e+00, -1.60982339e-14,
        7.54951657e-15, -2.66453526e-15,  1.06581410e-14,  1.00000000e+00,
        1.00000000e+00,  1.06581410e-14,  1.00000000e+00, -2.55351296e-15,
        1.00000000e+00, -2.99760217e-15,  1.00000000e+00, -1.64313008e-14,
        1.00000000e+00,  1.00000000e+00, -3.44169138e-15, -1.60982339e-14,
       -1.62092562e-14,  1.11022302e-14,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00,  1.04360964e-14,  1.04360964e-14,  1.00000000e+00,
        1.00000000e+00, -

In [ ]:
# which model is good for what conditions ?
# regularisation tech
# Gridsearch cv Randomised serch cv 
# 