In [ ]:
#numpy intro : 

In [2]:
import numpy as np

In [4]:
a=[1,34,67,90]
b=np.array(a)
b
b=np.array(a)
b

array([ 1, 34, 67, 90])

In [3]:
print(type(a))
print(type(b))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
print("total shape = ",b.shape)  ##shape = n(rows),n(columns)
print("total size = ",b.size)  ##total size of array= n(rows)*n(columns)
print("total dimension = ",b.ndim)  ##total dimension of array= n(rows)

total shape =  (4,)
total size =  4
total dimension =  1


In [5]:
a=[[1,2,3],[4,5,6],[7,8,9]]
b= np.array(a)
print(b)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print("total shape = ",b.shape)  ##shape = n(rows),n(columns)
print("total elements = ", b.size)  ##total size of array= n(rows)*n(columns)
print("total dimensions = ", b.ndim )  ##total dimension of array= n(rows)


total shape =  (3, 3)
total elements =  9
total dimensions =  2


In [7]:
#user defiend array
a=[]
size= int(input("enter size"))
for i in range(size):
    val = int(input("enter item: "))
    a.append(val)
b= np.array(a)
print(b)


enter size 12
enter item:  1
enter item:  1
enter item:  1
enter item:  1
enter item:  3
enter item:  4
enter item:  5
enter item:  6
enter item:  7
enter item:  7
enter item:  4
enter item:  6


[1 1 1 1 3 4 5 6 7 7 4 6]


In [8]:
#pre-defined function of numpy
#1.zeros--> returns an array of zeros, with shape defined by the parameter given
a= np.zeros(4)
print(a)

[0. 0. 0. 0.]


In [9]:
b=np.zeros((3,4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
#2.ones--> returns an array of ones, with shape defined by the parameter given
c= np.ones(4)
print(c)

d=np.ones((2,3))
print(d)


[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
#use cases of numpy
#images -->
#pixels(0-255) --> b&w images = height , width
#colourfull images = height , width , colour_channel(r,g,b)
#machine_learning --> actual_answer , prediction_answer ---> optimization techninque(m,b)

#3. eye() --> returns a 2D array with ones on the main diagonal and zeros elsewhere
e= np.eye( 4)
print(e)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
f= np.eye(3,4)
print(f)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [6]:
#4. diag()--> it will create an array in which we can set diagonal positional elements

In [7]:
a=np.array([1,3,5,5,2])
a

array([1, 3, 5, 5, 2])

In [8]:
b=np.diag(a)
b

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 2]])

In [9]:
#(5): random module

In [11]:
#a). Randint()-> randint(min_range , max_range , how many numbers u want)


In [3]:
a= np.random.randint(1,10,3)
a

array([6, 4, 7])

In [5]:
##b).Rand()->> it will generate random number in range 0-1.(how many number u want)
# it is fixed 

In [19]:

a=np.random.rand(4)
a

array([0.65624891, 0.05038032, 0.08838312, 0.19902847])

In [21]:
a = np.random.rand(2,3)

In [22]:
print(a)

[[0.38926846 0.40926768 0.42495507]
 [0.26255267 0.55289308 0.51592366]]


In [26]:
#c. SEED: --> it will fix our random generated data


In [7]:
np.random.seed(0)                                                           ########
a= np.random.randint(1,10,3)
a

array([6, 1, 4])

In [ ]:
#view vs copy           
#view---> modify in original data
#copy---> changes in duplicate entries
##### copy?

In [8]:
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [11]:
#view 
b=a[3:6]
b[:]= 0
b
a

array([10, 20, 30,  0,  0,  0, 70, 80, 90])

In [19]:
a=np.array([10,20,30,40,50,60,70,80,90])
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
#copy
b=a[3:6].copy()
b[:]=0
b
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
#conditional statements in numpy

In [37]:
a=np.arange(1,16,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [40]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [41]:
#reshaping the array

In [43]:
a= np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [44]:
b= np.array([1,2,3,4]).reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [45]:
a+b

array([[2, 4],
       [6, 8]])

In [46]:
a-b

array([[0, 0],
       [0, 0]])

In [48]:
a*b                  #wrong

array([[ 1,  4],
       [ 9, 16]])

In [49]:
a.dot(b)

array([[ 7, 10],
       [15, 22]])

In [50]:
a=np.random.randint(1,50,12)
a

array([ 5, 36,  6, 12, 43, 15, 30, 19, 30, 26, 30, 39])

In [25]:
#factors of 12 can make reshape of the array

In [54]:
a.reshape(3,4)

array([[ 5, 36,  6, 12],
       [43, 15, 30, 19],
       [30, 26, 30, 39]])

In [55]:
a.reshape(6,2)

array([[ 5, 36],
       [ 6, 12],
       [43, 15],
       [30, 19],
       [30, 26],
       [30, 39]])

In [29]:
#a.reshape(2,7)    
#will throw an error

In [57]:
a= np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.sum(a)  #sum of total elements

300

In [59]:
np.sum(a , axis = 0) #axis 0 = column wise

array([12, 15, 18])

In [60]:
np.sum(a,axis=1) #axis =1 = row wise

array([ 6, 15, 24])

In [61]:
#unique()---> it will create an array in which we have unique valuses

In [62]:
#retuen 3 array
#arr--> unique array
#reteun_index = True ---> unique values indexing
#return_counts = True---> unique values frequency

In [64]:
a= np.array([1,2,3,4,5,6,6,6,7,7,7,7,7,7,3])
a

array([1, 2, 3, 4, 5, 6, 6, 6, 7, 7, 7, 7, 7, 7, 3])

In [65]:
np.unique(a,return_index = True , return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7]),
 array([0, 1, 2, 3, 4, 5, 8], dtype=int64),
 array([1, 1, 2, 1, 1, 3, 6], dtype=int64))

In [66]:
#linspace ---> it will return same gap values from a given range

In [68]:
a= np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [69]:
#1.25 - 1 = 0.25
# 2.5 - 1.25 = 0.25 
# 1.75 - 1.5 =0.25
# 2- 1.75 = 0.25


In [70]:
#stacking 
#(1). HSTACK()-->
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
np.hstack((a,b,c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
#(2). VASTACK()--->
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
np.vstack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#array is used to perform operations on all of its elements 

In [72]:
#create an array using numpy?
#create an array of 10 random integers?
#create an array of elements from 10-20?
#create an array which contains value 5,10 times ?
#create a one d array and convert that into 3*3 matrix
#create a 2d array of size 3*3 but all the elements should be b/w 0 to 1?
#concatenate 2d array horizontally and vertically?

In [73]:
#create an array using numpy?
a= np.array([1,3,4])
a

array([1, 3, 4])

In [78]:
#create an array of 10 random integers?
a= np.random.randint(1,10,10)
a

array([1, 6, 5, 4, 4, 6, 6, 9, 9, 5])

In [81]:
#create an array of elements from 10-20?
a= np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [84]:
#create an array which contains value 5,10 times ?
a= np.repeat(5,10)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [14]:
# create a one d array and convert that into 3*3 matrix
b= np.arange(1,10)
b
c=b.reshape(3,3)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [100]:
#create a 2d array of size 3*3 but all the elements should be b/w 0 to 1?
e= np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#concatenate 2d array horizontally and vertically?
a= np.array([[1,2,3] , [4,5,6]])
b = np.concatenate((a,a), axis=0)
c = np.concatenate((a, a), axis=1)
b
c

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [108]:
print(c)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [12]:
x = {1,2,3}
y = {3,4,5}
print(x & y)

{3}
